title: Awesome Endo and Adeno Resources
remote_theme: "jekyll/minima@1e8a445"
markdown: GFM 
minima:
  skin: auto

# Site configuration
url: "" # Leave empty for local development
baseurl: "" # Leave empty for root domain

# Build settings
source: .
destination: _site
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'vendor/bundle', 'vendor/cache', 'vendor/gems', 'vendor/ruby']

# Enable GitHub Pages and Jekyll
github:
  pages:
    enabled: true
    build: true
